from django.forms import ModelForm
from django import forms

from engage_app.models import SystemMessage


class SystemMessageForm(ModelForm):
    # Make the slug field not required since we will be generating that if left blank
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['slug'].required = False

    class Meta:
        model = SystemMessage
        fields = ['slug', 'type', 'title', 'content']
        exclude = ['author', 'created_at']
        widgets = {
            "slug": forms.TextInput(attrs={'placeholder': '<will be autogenerated>'})
        }
