# Generated by Django 3.2.9 on 2022-06-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='source',
        ),
        migrations.AddField(
            model_name='notification',
            name='source_id',
            field=models.IntegerField(null=True),
        ),
    ]
