# Generated by Django 3.2.9 on 2023-01-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('engage_app', '0015_01_04_2023'),
        ('communication_app', '0003_08_02_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionboard',
            name='research_project',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='research_project_discussion', to='engage_app.researchproject'
            ),
        ),
        migrations.AlterField(
            model_name='discussionboard',
            name='parent_task',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='parent_research_task', to='engage_app.researchprojecttask'
            ),
        ),
    ]
