# Generated by Django 3.2.9 on 2023-01-24 02:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('communication_app', '0004_auto_20230103_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communication_app.message'
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='picture_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='users_that_liked_message',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=255, default=list
            ),
        ),
        migrations.AddField(
            model_name='message',
            name='users_that_read_message',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=255, default=list
            ),
        ),
        migrations.CreateModel(
            name='UserMessageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='user_message_tagged_message',
                                              to='communication_app.message')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user_tagged_in_message', to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
