# Generated by Django 3.2.9 on 2023-04-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_app', '0005_auto_20230124_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
