# Generated by Django 3.2.9 on 2023-07-18 15:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from engage_app.utils.constants import SystemMessageTypes


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication_app', '0006_alter_notification_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=SystemMessageTypes.to_list(), max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_message_user', to=settings.AUTH_USER_MODEL)),
                ('is_published', models.BooleanField(default=False)
                ),
            ],
        ),
    ]
