# Generated by Django 3.2.9 on 2022-04-05 14:32

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid

from engage_app.utils import UserRoles, QuestionTypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('title', models.TextField(max_length=255)),
                ('reference_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('icu_city', models.TextField(blank=True, null=True)),
                ('icu_country', models.TextField(blank=True, null=True)),
                ('partner_commitment_time', models.FloatField(blank=True, default=2.0, null=True)),
                ('partner_commitment_period', models.TextField(blank=True, choices=[('DAY', 'daily'), ('WEEK', 'weekly'), ('MONTH', 'monthly'), ('YEAR', 'yearly')], default='weekly', null=True)),
                ('roles_needed', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=UserRoles.to_list(), null=True), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_link', models.URLField(blank=True, default='', null=True)),
                ('twitter_link', models.URLField(blank=True, default='', null=True)),
                ('facebook_link', models.URLField(blank=True, default='', null=True)),
                ('instagram_link', models.URLField(blank=True, default='', null=True)),
                ('research_gate_link', models.URLField(blank=True, default='', null=True)),
                ('website_link', models.URLField(blank=True, default='', null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProjectOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('mapping', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchProjectQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dev_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('order_number', models.SmallIntegerField()),
                ('type', models.CharField(choices=QuestionTypes.to_list(), max_length=200)),
                ('is_required_researcher', models.BooleanField(default=False)),
                ('is_required_patient', models.BooleanField(default=False)),
                ('is_required_family_of_patient', models.BooleanField(default=False)),
                ('is_required_passive', models.BooleanField(default=False)),
                ('text_for_researcher', models.CharField(blank=True, max_length=600, null=True)),
                ('text_for_patient', models.CharField(blank=True, max_length=600, null=True)),
                ('text_for_family_of_patient', models.CharField(blank=True, max_length=600, null=True)),
                ('text_for_caretaker_of_patient', models.CharField(blank=True, max_length=600, null=True)),
                ('text_for_passive', models.CharField(blank=True, max_length=600, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('display_text', models.TextField(null=True, blank=True)),
                ('linked_to_research_interest', models.BooleanField(default=False, null=True, blank=True)),
                ('is_displayed_in_profile_variables', models.BooleanField(default=True, null=True, blank=True)),
                ('is_searchable', models.BooleanField(default=True, null=True, blank=True)),
                ('placeholder_text', models.TextField(null=True, blank=True)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engage_app_researchprojectquestion_parent_question', to='engage_app.researchprojectquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchProjectSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2500)),
                ('order_number', models.SmallIntegerField()),
                ('is_valid_researcher', models.BooleanField()),
                ('is_valid_patient', models.BooleanField()),
                ('is_valid_family_of_patient', models.BooleanField()),
                ('is_valid_caretaker_of_patient', models.BooleanField()),
                ('is_valid_passive', models.BooleanField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchProjectQuestionOptionDependency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dependant_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_project_dependant_question', to='engage_app.researchprojectquestion')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_project_parent_option', to='engage_app.researchprojectoption')),
            ],
        ),
        migrations.AddField(
            model_name='researchprojectquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engage_app.researchprojectsection'),
        ),
        migrations.CreateModel(
            name='ResearchProjectParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_patient_partner', models.BooleanField(default=False)),
                ('is_research_partner', models.BooleanField(default=False)),
                ('is_principal_investigator', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engage_app_researchprojectparticipant_related_project', to='engage_app.researchproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engage_app_researchprojectparticipant_related_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='researchprojectoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engage_app.researchprojectquestion'),
        ),
        migrations.CreateModel(
            name='ResearchProjectAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=200), default=list, size=None)),
                ('comment', models.TextField(default='', max_length=400)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_project_answered_question', to='engage_app.researchprojectquestion')),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engage_app.researchproject')),
            ],
            options={
                'unique_together': {('question', 'research_project')},
            },
        ),
    ]
