# Generated by Django 3.2.9 on 2022-07-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_07_18_2022'),
        ('engage_app', '0008_06_29_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='research_interests',
            field=models.ManyToManyField(to='auth_app.ResearchInterest'),
        ),
    ]
