# Generated by Django 3.2.9 on 2022-08-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_07_18_2022'),
        ('engage_app', '0009_07_18_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProjectTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_protocol_file', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engage_app_researchprojecttaskfile_parent_task', to='engage_app.researchprojecttask')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engage_app_researchprojecttaskfile_uploader', to='auth_app.userprofile')),
            ],
        ),
    ]
