# Generated by Django 3.2.9 on 2022-08-05 18:56

from django.db import migrations, models
import engage_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0010_08_01_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchprojecttaskfile',
            name='file',
            field=models.FileField(
                blank=True, null=True, upload_to='tmp',
                validators=[engage_app.validators.validate_file_extension]
            ),
        ),
    ]
