# Generated by Django 3.2.9 on 2023-01-03 16:38

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models

from engage_app.utils import UserRoles


class Migration(migrations.Migration):
    dependencies = [
        ('engage_app', '0012_08_08_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='roles_needed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(
                choices=UserRoles.get_project_partner_types(), null=True
            ), size=None),
        ),
        migrations.CreateModel(
            name='ResearchProjectTaskAssignedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='research_task_assigned_user',
                                                    to=settings.AUTH_USER_MODEL)),
                ('research_project_task',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_research_project',
                                   to='engage_app.researchprojecttask')),
            ],
            options={
                'unique_together': {('research_project_task', 'assigned_user')},
            },
        ),
    ]
