# Generated by Django 3.2.9 on 2023-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0015_01_04_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprojecttask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
