# Generated by Django 3.2.9 on 2023-03-05 19:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from engage_app.utils import ResearchStudyFormats


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engage_app', '0020_auto_20230303_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='researchproject',
            name='main_contact',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='project_contact', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='study_format',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, choices=ResearchStudyFormats.to_list(), null=True),
                blank=True, max_length=2, null=True, size=None
            ),
        ),
    ]
