# Generated by Django 3.2.9 on 2023-03-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('engage_app', '0022_alter_researchprojectsection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprojecttask',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchprojecttaskassigneduser',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
