# Generated by Django 3.2.9 on 2023-03-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0025_create_research_project_questions_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchproject',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='goal_of_project',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='summary',
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
