# Generated by Django 3.2.9 on 2023-04-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0026_auto_20230330_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprojectparticipant',
            name='is_project_lead',
            field=models.BooleanField(default=False),
        ),
    ]
