# Generated by Django 3.2.9 on 2023-04-27 00:30

from django.db import migrations, models
from engage_app.utils import DateTypes


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0028_add_project_reminder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='end_date_type',
            field=models.TextField(blank=True, choices=DateTypes.to_list(), null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='is_using_end_date',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='is_using_start_date',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='start_date_type',
            field=models.TextField(blank=True, choices=DateTypes.to_list(), null=True),
        ),
    ]
