# Generated by Django 3.2.9 on 2023-05-17 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0029_add_start_end_date_type_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchprojectcalendarreminder',
            name='research_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_research_project', to='engage_app.researchproject'),
        ),
    ]
