# Generated by Django 3.2.9 on 2023-09-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0033_research_project_add_field_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='type',
            field=models.CharField(choices=[('NOTIFICATION', 'Notification'), ('BLOG', 'Blog')], max_length=64),
        ),
    ]
