# Generated by Django 3.2.9 on 2023-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0036_update_calendar_reminder_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprojecttaskfile',
            name='url',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
