# Generated by Django 3.2.9 on 2023-10-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0037_researchprojecttaskfile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprojecttask',
            name='hide_submitted_files',
            field=models.BooleanField(default=False),
        ),
    ]
