# Generated by Django 3.2.9 on 2023-08-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0036_userprofilequestion_research_interest_category'),
        ('engage_app', '0039_researchprojecttask_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprojectquestion',
            name='research_interest_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_app.researchinterestcategory'),
        ),
    ]
