# Generated by Django 3.2.9 on 2023-10-16 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from engage_app.utils import EngageReportTypes


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engage_app', '0041_researchprojectquestion_category_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngageReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=EngageReportTypes.to_list(), max_length=64)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engage_report_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
