# Generated by Django 3.2.9 on 2023-10-31 17:37

from django.db import migrations, models

from engage_app.utils.constants import SystemMessageTypes


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0042_engagereports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='type',
            field=models.CharField(choices=SystemMessageTypes.to_list(), max_length=64),
        ),
    ]
