# Generated by Django 3.2.9 on 2023-11-06 18:02

from django.db import migrations, models
from engage_app.utils import DateTypes


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0043_alter_systemmessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprojecttask',
            name='due_date_type',
            field=models.TextField(blank=True, choices=DateTypes.to_list(), null=True),
        ),
        migrations.AddField(
            model_name='researchprojecttask',
            name='is_using_due_date',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
