# Generated by Django 3.2.9 on 2023-11-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0045_update_existing_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
