# Generated by Django 3.2.9 on 2023-12-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engage_app', '0047_researchprojectparticipant_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprojecttaskassigneduser',
            name='is_prompted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchprojecttaskassigneduser',
            name='prompted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
