# Generated by Django 3.2.9 on 2022-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_31_05_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
