# Generated by Django 3.2.9 on 2022-11-09 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0008_29_07_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchinterest',
            name='clinical_area',
        ),
        migrations.AddField(
            model_name='researchinterest',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='researchinterest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchinterest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchinterest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchinterest',
            name='parent_interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.researchinterest'),
        ),
        migrations.AddField(
            model_name='researchinterest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
