# Generated by Django 3.2.9 on 2022-11-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('auth_app', '0009_auto_20221109_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='edi_answers_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='icu_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cities_light.city'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='researchinterest',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
