# Generated by Django 3.2.9 on 2023-03-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth_app', '0014_default_research_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofilequestion',
            name="is_mandatory",
            field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name='userprofilequestion',
            name="display_text",
            field=models.TextField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name='userprofilequestion',
            name="linked_to_research_interest",
            field=models.BooleanField(default=False, null=True, blank=True)
        ),
        migrations.AddField(
            model_name='userprofilequestion',
            name="is_displayed_in_profile_variables",
            field=models.BooleanField(default=True, null=True, blank=True)
        ),
        migrations.AddField(
            model_name='userprofilequestion',
            name="is_searchable",
            field=models.BooleanField(default=True, null=True, blank=True)
        ),
        migrations.AddField(
            model_name='userprofilequestion',
            name="placeholder_text",
            field=models.TextField(null=True, blank=True)
        )
    ]
