# Generated by Django 3.2.9 on 2023-03-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_initial_user_profile_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='edi_answers_public',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='has_disability',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_identified_native',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_visible_minority',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='most_used_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='population_group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sexual_orientation',
        ),
    ]
