# Generated by Django 3.2.9 on 2023-03-15 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_auto_20230308_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='icu_institute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pronouns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icu_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cities_light.city'),
        ),
    ]
