# Generated by Django 3.2.9 on 2023-03-22 15:55

import django.contrib.postgres.fields
from django.db import migrations, models


def convert_pronouns_to_array_field(apps, schema_editor):
    UserProfile = apps.get_model("auth_app", "UserProfile")

    for user_profile in UserProfile.objects.all():
        if user_profile.pronouns and user_profile.pronouns != '':
            user_profile.pronouns = [user_profile.pronouns_old]
            user_profile.save()


def reverse_convert_pronouns(apps, schema_editor):
    UserProfile = apps.get_model("auth_app", "UserProfile")
    for user_profile in UserProfile.objects.all():
        if user_profile.pronouns and len(user_profile.pronouns) > 0:
            user_profile.pronouns_old = user_profile.pronouns[0]
            user_profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ('auth_app', '0018_auto_20230315_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pronouns',
            new_name='pronouns_old',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pronouns',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True), blank=True, null=True, size=None
            ),
        ),
        migrations.RunPython(convert_pronouns_to_array_field, reverse_code=reverse_convert_pronouns),
        migrations.RemoveField(model_name='userprofile', name="pronouns_old")
    ]
