# Generated by Django 3.2.9 on 2023-04-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_auto_20230322_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_minimum_profile_check_valid',
            field=models.BooleanField(default=False),
        ),
    ]
