# Generated by Django 3.2.9 on 2023-04-24 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0020_userprofile_is_minimum_profile_check_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('faq_type', models.CharField(choices=[], max_length=50)),
                ('liked_users', models.ManyToManyField(related_name='liked_faqs', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed_users', models.ManyToManyField(related_name='viewed_faqs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
