# Generated by Django 3.2.9 on 2023-03-10 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from auth_app.utils import ContactEnquiryTypes, SupportScreens


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0022_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=320)),
                ('enquiry_type', models.CharField(choices=ContactEnquiryTypes.to_list(), max_length=100)),
                ('support_screen', models.CharField(choices=SupportScreens.to_list(), max_length=100, blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
