# Generated by Django 3.2.9 on 2023-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_contactlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('ACCOUNT', 'Account Settings')], max_length=50),
        ),
    ]
