# Generated by Django 3.2.9 on 2023-07-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_admin_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileoption',
            name='order_number',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
