# Generated by Django 3.2.9 on 2023-09-22 15:00

import auth_app.utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_icu_hospitals_research_interest_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='screenshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='bool_value',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='data_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('BOOLEAN', 'Boolean'), ('INTEGER', 'Integer'), ('DATETIME', 'Datetime')], default=auth_app.utils.constants.ADMIN_SETTINGS_TYPE['TEXT'], max_length=10),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
