# Generated by Django 3.2.9 on 2023-07-31 17:15

from auth_app.utils.constants import ADMIN_SETTINGS_TYPE
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_insight_scope_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInterestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('mapping', models.TextField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True))
            ],
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='bool_value',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='data_type',
            field=models.CharField(
                choices=ADMIN_SETTINGS_TYPE.to_list(),
                default=ADMIN_SETTINGS_TYPE['TEXT'],
                max_length=10
            ),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        )
    ]
